spring:
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:mariadb://mariadb:3306/epik"
    username: "root"
    password: "secret"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
        format_sql: true
  application:
    name: epik-task

server:
  port: 8080

logging:
  logTimeExec: true
  file:
    name: log/epik-task.log
    max-size: 1MB

api:
  key: epik-api-key
